### ISSUE TITLE
Public files API for connection with BIIGLE

### ISSUE THREAD

**Issue by mzur** [elements-storage/elements-sdk-python#1]
Hi, I'm working with GEOMAR to establish a connection between ELEMENTS and the image annotation software [BIIGLE](https://github.com/biigle). I explored the available ELEMENTS API endpoints but they're so many that I thought asking would be quicker.

Is there a way to make files accessible through a public URL? So for example if I have a directory `Test` with the files `1.jpg` and `2.jpg` I can access the raw files through URLs like `https://myelements.com/api/2/raw-files/Test/1.jpg` and `https://myelements.com/api/2/raw-files/Test/2.jpg`. Is this possible?

**Comment by Eugeny** [comment]
Hi Martin, in v3.1+, you can generate a direct link to the original file or the proxy through the [share_media_library_objects](https://python.sdk.elements.tv/docs/MediaLibraryApi#share_media_library_objects) request (`/api/2/media/share`).

```
{
    bundles: [252]
    directories: []
    expires: "2021-08-26T22:00:00.941Z"
    link_type: "download-proxy"
    permissions: {}
    view_limit: null
}
```

It returns a [OneTimeAccessToken](https://python.sdk.elements.tv/docs/OneTimeAccessToken) object.

Set `bundles` to the Bundle ID corresponding to the file (you can get it through [get_asset](https://python.sdk.elements.tv/docs/MediaLibraryApi.html#get_asset) or [get_media_file](https://python.sdk.elements.tv/docs/MediaLibraryApi.html#get_media_file)). 

Other possible values for `link_type` are `download-original`, `embed-player` and `embed-full` (for iframe embedding).

This is the same request that is used for "share via link" function in the UI.

**Comment by mzur** [comment]
Thanks @Eugeny! I've also discovered this feature for a single file in the UI. The `download-original` type seems to be what I am looking for. However, I need this for a whole directory and not only individual files. If I create a share link for multiple files, I can't choose the link type any more in the UI. Also, can `expires` be unlimited?

I'm also exploring an alternative idea in case the public link is a dead end for BIIGLE. If I assume that I can make an API request authenticated via API token and the authenticated user has access to the files, can I get a direct download of the file if I only know the file path (e.g. `Test/1.jpg`) and not the file ID?

**Comment by Eugeny** [comment]
The only way to download multiple files in one go is via a download archive (i.e. how the "Download original" / "Download proxy" buttons work with multiple selected files).

`expires` is required, but can be set to year 2999 ;)

When you're authenticated via a token, downloading files becomes much easier - you can access the original directly through [download_media_file](https://python.sdk.elements.tv/docs/MediaLibraryApi#download_media_file) and the proxy URL is available through the `.default_proxy.urls.proxy` property on an `Asset`. Both are direct downloads and support Content-Range based streaming when the file is a video.

In both cases you still need to get the file ID first via e.g. [get_all_media_files](https://python.sdk.elements.tv/docs/MediaLibraryApi#get_all_media_files) with `volume` and `path` params.

If you absolutely must have a direct URL for a given path in "one go", you'd have to build a small web service to fetch the file ID and return/proxy the URL (the service could then run on the system itself).

**Comment by mzur** [comment]
Looks like the second option is the way to go. I'm now thinking about implementing a Laravel storage disk adapter for Elements, so BIIGLE (or any Laravel app) can treat an Elements instance like a file system.

It could even work with temporary direct download links that are automatically created per-file. Is there a way to configure the `Access-Control-Allow-Origin` header for cross origin resource sharing of files served by an Elements instance?

**Comment by Eugeny** [comment]
No, CORS isn't supported. Are you planning do non-GET requests to the API directly from the browser? Otherwise CORS headers are not required for file downloads (via GET requests).

**Comment by mzur** [comment]
> Are you planning do non-GET requests to the API directly from the browser? Otherwise CORS headers are not required for file downloads (via GET requests).

Not quite. If you GET an image and then want to do some in-browser processing (e.g. brightness/contrast adjustment) then CORS is required for cross-origin images. If CORS is not supported then maybe I won't work on support for temporary direct download links for now.

Thanks again for your help!

**Comment by Eugeny** [comment]
Actually, here's an idea: you can inject CORS headers globally (for every response from the system) via a custom NGINX config in `/etc/elements` - see how files are included in `/etc/nginx/conf.d/elements.conf`

**Comment by mzur** [comment]
Thanks! I'll suggest this to the GEOMAR people if and when I implement the adapter.

**Comment by mzur** [comment]
Just one more question. Is there a way to get the MIME type of a file? I couldn't find it in the output of `media/assets` or `media/files`.

**Comment by Eugeny** [comment]
Not a MIME type, but `MediaAsset.info` contains all sorts of format information.

**Comment by mzur** [comment]
So the MIME type is not stored in Elements at all?

**Comment by Eugeny** [comment]
No - we're not using it anywhere.

**Comment by mzur** [comment]
Sorry to keep bothering you. Is `download_media_file` only available for newer versions of Elements?

**Comment by Eugeny** [comment]
No worries. This V2 endpoint is new in v3.3. If you're below that, you'll need to use the corresponding V1 endpoint - see where the request goes to in Devtools when downloading a file from the UI.

**Comment by mzur** [comment]
Another question if I may (or do you prefer another communication channel)?

Currently the [adapter](https://github.com/biigle/flysystem-elements) uses the `api/2/media/files` endpoint to get the file ID and then `api/media/download/:id` (as the V2 endpoint is not available on the target instance) to download the file. This works for many images that I've tested. But now it doesn't work for a video. If I click "Download Original File" in the UI, the download link is constructed with the "bundle" ID instead of the file ID. The download with the file ID results in "access denied" whereas the bundle ID works.

Does this have something to do with the access permissions configured in Elements or is this maybe something special for videos?

**Comment by Eugeny** [comment]
The `api/media/download` V1 endpoint has always taken a bundle ID, not a file ID. If it worked for some files, then it's a mere coincidence that their file and bundle IDs were equal.

**Comment by mzur** [comment]
Ok, thanks a lot! And the "bundle" is just the single file in this case and not a collection of files?

**Comment by Eugeny** [comment]
Yes - in your case (single pictures and videos) bundles will consist of a single file.

**Comment by mzur** [comment]
Final question (I hope): If I create a share link via `api/2/media/share`, is there a way to obtain a direct download link that skips the "download will begin shortly" view? E.g. if I use something like `auth/fast-lane/xxxx?direct=true` I get directly redirected to `api/media/stream/xxx/proxy.1.default.mp4` instead of `download-redirect`? The idea is to use the link directly as `src` of an image or a video element.

**Comment by Eugeny** [comment]
No, this isn't possible
